services:
  app:
    build: .
    container_name: go-rest-gin
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/
    depends_on:
      - postgres
    environment:
      - HOST_OS=mac

  postgres:
    image: postgres:17-alpine3.20
    container_name: go-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
